// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arkmxuyjwzyldguzlbnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFya214dXlqd3p5bGRndXpsYm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDA5NTEsImV4cCI6MjA2NDM3Njk1MX0.He0jIAE4FQXmB7Djybz_yaGsaptGrXnQaPj2OA_vxjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);